---
- hosts: jenkins-osx-slaves
  become: True
  tasks:
    - name: 'uninstall awscli'
      pip:
        name: 'awscli'
        state: absent
    - name: 'uninstall pip'
      pip:
        name: 'pip'
        state: absent
    - name: 'remove jenkins user'
      user:
        name: 'jenkins'
        state: absent
    - name: 'remove jenkins group'
      group:
        name: 'jenkins'
        state: absent
    - name: 'remove jenkins user home directory'
      file:
        path: /Users/jenkins
        state: absent
    - name: 'uninstall java'
      homebrew_cask:
        name: java8
        state: absent
      become: yes
      become_user: qamaidsafe
    - name: 'uninstall caskroom/versions'
      homebrew_tap:
        name: caskroom/versions
        state: absent
    - name: 'stop wireguard (not a problem if this errors)'
      command: wg-quick down wg0
      ignore_errors: yes
    - name: 'uninstall wireguard'
      homebrew:
        name: wireguard-tools
        state: absent
